timeout 60;
retry 10;
reboot 10;
select-timeout 5;
initial-interval 2; 
script "/sbin/dhclient-script";  
send host-name "2102313NNLP0NC100035";
send dhcp6.client-id = concat(00:03:00, hardware);
request subnet-mask, broadcast-address, time-offset, routers;
#require subnet-mask, domain-name-servers;
request dhcp6.sntp-servers;
