
user  apache;

worker_processes  2;

error_log  logs/error_log info;

worker_rlimit_nofile 256;
events {
    worker_connections  128;
}


http {
    server_names_hash_bucket_size 256;
    include       mime.types;

    sendfile                  on;
    port_in_redirect          off;
    default_type              application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  logs/access_log  main;

    proxy_read_timeout        15m;
    proxy_connect_timeout     15m;
    proxy_send_timeout        15m;

    # Security connection
    keepalive_timeout         16s;
    send_timeout              10s;
    client_body_timeout       6m;
    client_header_timeout     60s;
    client_max_body_size      100m;
    client_header_buffer_size 8k;
    limit_conn_zone $binary_remote_addr zone=limitperip:10m;
    large_client_header_buffers 64 1k;
    ssl_session_tickets off;

    # Security header
    add_header X-Frame-Options DENY;
    add_header X-Download-Options noopen;
    add_header X-XSS-Protection "1;mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' wss://*:*; img-src 'self' data:; frame-src 'self'; font-src 'self' data:; object-src 'self'; style-src 'self' 'unsafe-inline'";
    add_header Cache-control "no-cache, no-store, must-revalidate";
    add_header Pragma no-cache;
    add_header Expires 0;
    proxy_hide_header     X-Powered-By;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Referrer-Policy "no-referrer";

    # Customized configuration
    add_header ETag $sent_http_etag;

    upstream webrest {
        server 127.0.0.1:30080;
    }

    upstream redfish_proxy {
        server 127.0.0.1:30080;
    }

    include nginx_http_server.conf;

    include nginx_https_server.conf;
}
