options {
send_time_zone("+00:00");
};
destination d_pme_dfm_debug { file("/var/log/pme/dfm_debug_log" time_zone("+00:00")); };
destination d_pme_security { file("/var/log/pme/security_log" perm(0640) group(103) time_zone("+00:00")); };
destination d_kern { file("/var/log/pme/linux_kernel_log" time_zone("+00:00")); };
filter f_driver   { facility(kern) and level(notice) and match("edma" value("MESSAGE")); };
destination d_driver { file("/var/log/pme/agentless_driver_log" perm(0640) ); };
log { source(s_kern); filter(f_driver); destination(d_driver); };
