timeout 60;
retry 10;
reboot 10;
select-timeout 5;
initial-interval 2; 
script "/sbin/dhclient-script";  
send host-name "2102313NNLP0NC100035";
request subnet-mask, broadcast-address, time-offset, routers,
                domain-name, domain-name-servers, ntp-servers;
#require subnet-mask, domain-name-servers;
