send dhcp6.client-id = concat(00:03:00, hardware);
tsend rapid-commit;trequest prefix-delegation;trequest domain-name-servers;trequest domain-search-list;trequest
temp-address;tiaid 11111;taddress {tt3ffe:10::10/64;ttprefer-life-time 6000;ttvalid-life-time
8000;t};trenew-time 11000;trebind-time 21000;
request dhcp6.sntp-servers;
send host-name "2102313NNLP0NC100035";
